---
title: "Section 2: Intro to Plotting with ggplot"
author: "Matt Higham"
format: 
  html:
    embed-resources: true
---

## Section 2.2: Basic Plot Structure

```{r}
library(tidyverse)
stat113_df <- read_csv("https://raw.githubusercontent.com/highamm/ds234_quarto/main/data_online/stat113.csv")

ggplot(data = stat113_df, aes(x = GPA)) +
  geom_histogram()

ggplot(data = stat113_df, aes(x = GPA)) +
  geom_histogram(colour = "black", fill = "white", bins = 17)

ggplot(data = stat113_df, aes(x = GPA)) +
  geom_freqpoly(bins = 17)
```

#### Exercises 1 - 3

```{r}
names(stat113_df)
stat113_df
ggplot(data = stat113_df, aes(x = Exercise)) +
  geom_histogram(colour = "lightpink2", fill = "lightpink")
```

Exercises 4 through 6

```{r}
ggplot(data = stat113_df, aes(x = Sport)) +
  geom_bar(colour = "darkorange", fill = "darkorange4")

ggplot(data = stat113_df, aes(x = Year, fill = Sex)) +
  geom_bar(position = "fill") +
  labs(y = "Proportion")
```

Exercises 7 and 8


#### Section 2.4

Class Exercises

Class Exercise 1.

```{r}
ggplot(data = stat113_restructured,
       aes(x = SocialMedia)) +
  geom_bar()

ggplot(data = stat113_restructured,
       aes(x = SocialMedia, y = n_social)) +
  geom_col()
```

Class Exercises 2 through 5.

```{r}
library(tidyverse)
fitness_full <- read_csv("https://raw.githubusercontent.com/highamm/ds234_quarto/main/data_online/higham_fitness_clean.csv",
                         col_types = list(stepgoal = col_factor())) |>
  mutate(weekend_ind = case_when(weekday == "Sat" | weekday == "Sun" ~ "weekend",
                                 .default = "weekday"))

ggplot(data = fitness_full, aes(x = distance, y = active_cals)) +
  geom_point() +
  geom_smooth(span = 1.1,
              se = FALSE)

## method = "lm" makes a best fit line
## se = FALSE gets rid of the gray error band
## span controls how "wiggly" the smoother is
```

```{r}
ggplot(data = stat113_df,
       aes(x = Exercise,
           y = GPA)) +
  geom_point() +
  facet_wrap(~ Sex + Sport)

ggplot(data = stat113_df,
       aes(x = Exercise,
           y = GPA)) +
  geom_point() +
  facet_grid(Sex ~ Sport)

ggplot(data = stat113_df, aes(x = Award, y = Exercise)) +
  geom_boxplot(outlier.shape = 8)
```

Class Exercise 6. Skip.

