---
title: "Section 6: Tidying"
author: "Matt Higham"
format: 
  html:
    embed-resources: true
---

```{r}
library(tidyverse)
library(here)
```


## Class Exercises

Class Exercise 2.

```{r}
prices_df <- read_csv(here("data/UBSprices2.csv"))
prices_df
## this violates (1): each variable must be in its own column but
## year and commodity two variables in one column
```

Class Exercises 3 and 4.

```{r}
prices_tidy <- prices_df |> pivot_longer(2:7, names_to = "temp",
                          values_to = "price") |>
  separate(temp, c("commodity", "year"), sep = -4)
prices_tidy

prices_rice <- prices_tidy |> filter(commodity == "rice")
ggplot(data = prices_rice, aes(x = year, y = price)) +
  geom_line(aes(group = city))

## ce 4
prices_amsterdam <- prices_tidy |> filter(city == "Amsterdam")
ggplot(data = prices_amsterdam, aes(x = year, y = price)) +
  geom_line(aes(group = commodity, colour = commodity)) +
  scale_colour_viridis_d() +
  theme_minimal()
```

Class Exercises 5-7

```{r}
mortality_df <- read_csv(here("data/under5mortality.csv"))
mortality_df

mortality_long <- mortality_df |> pivot_longer(2:217, names_to = "year",
                             values_to = "mortality") |>
  rename(country = `Under five mortality`) |>
  mutate(year = as.numeric(year))

ggplot(data = mortality_long, aes(x = year, y = mortality)) +
  geom_line(aes(group = country), alpha = 0.2)
## some lines might be flat if the data was using a mortality
## estimate for the entire century
```

Your Turns

```{r}
library(tidyverse)
library(here)
baseball_df <- read_csv(here("data/mlb2016.csv"))
glimpse(baseball_df)
baseball_df
## violates 4: some variables have units ($) when they shouldn't
## violates 1: the Years variable actually contains 3 different variables: 
## duration, start year, end year
```

Your Turns 2-4

```{r}
baseball_df <- baseball_df |> separate(Years, c("duration", "temp"), sep = " ") |>
  separate(temp, c("Start", "End"), sep = "-")

## warning message that some rows do not have an end year (these are one year contracts)

## yt 4
baseball_df <- baseball_df |>
  mutate(Salary = parse_number(Salary),
         Total.Value = parse_number(Total.Value),
         Avg.Annual = parse_number(Avg.Annual),
         Start = parse_number(Start),
         End = parse_number(End))
baseball_df
```

```{r}
## BAD plot: showing the total salary for each position-
## SP is really inflated because there are so many in the data set
ggplot(data = baseball_df, aes(x = POS, y = Salary)) +
  geom_col()

ggplot(data = baseball_df, aes(x = POS, y = Salary)) +
  geom_boxplot()
ggplot(data = baseball_df, aes(x = POS, y = Salary)) +
  geom_violin()
ggplot(data = baseball_df, aes(x = Salary)) +
  geom_histogram(colour = "skyblue4", fill = "skyblue1", bins = 15) +
  facet_wrap(~POS)
```


Your Turn 6.

```{r}
nfl_df <- read_csv(here::here("data/nfl_salary.csv"))
nfl_df
```

Not tidy: not every variable is in its own column. There should be columns for position and there should be a column for salary.

Your Turn 7

```{r}
nfl_long <- nfl_df |> pivot_longer(2:11,
                                   names_to = "position",,
                       values_to = "salary")
nfl_max <- nfl_long |> group_by(position, year) |>
  summarise(max_salary = max(salary, na.rm = TRUE))
nfl_max

## OR
nfl_max2 <- nfl_long |> group_by(position, year) |>
  filter(salary == max(salary, na.rm = TRUE))
## OR
nfl_max3 <- nfl_long |> group_by(position, year) |>
  arrange(desc(salary)) |>
  slice(1)

ggplot(data = nfl_max, aes(x = year, y = max_salary)) +
  geom_line(aes(colour = position))
```

Your Turn 8. Make this same plot, but this time, for the average of the top 32 highest paid players for each position.

```{r}
nfl_32 <- nfl_long |> group_by(position, year) |>
  arrange(desc(salary)) |>
  slice(1:32) |>
  summarise(mean_sal = mean(salary))

ggplot(data = nfl_32, aes(x = year, y = mean_sal)) +
  geom_line(aes(group = position)) +
  facet_wrap(~ position) +
  theme_minimal() +
  labs(title = "Avg. for Top 32 Players")
```

Your Turn 10.

```{r}
## assuming 1.59 is the inflation rate
nfl_adj <- nfl_long |> filter(year == 2011 | year == 2018) |>
  mutate(salary_adj = if_else(year == 2011,
                              true = salary * 1.59,
                              false = salary)) |>
  group_by(position, year) |>
  arrange(desc(salary_adj)) |>
  slice(1:32) |>
  summarise(mean_sal = mean(salary_adj))

ggplot(data = nfl_adj, aes(x = year, y = mean_sal)) +
  geom_line() +
  facet_wrap(~ position)
```


Your Turn 11.

```{r}
nfl_rank <- nfl_long |> filter(year == 2018) |>
  group_by(position) |>
  mutate(salary_rank = rank(desc(salary)))

ggplot(data = nfl_rank, aes(x = salary_rank, y = salary)) +
  geom_line(aes(colour = position), show.legend = FALSE) +
  ## show.legend = FALSE hides the legend (it's not necessary to have 
  ## a legend here)
  facet_wrap(~position) +
  theme_minimal() +
  scale_colour_viridis_d()

library(babynames)
babynames10 <- babynames |> filter(year == 2017 & sex == "F") |>
  arrange(desc(n)) |>
  slice(1:10) |>
  mutate(name2 = fct_reorder(name, n))
ggplot(data = babynames10, aes(x = n, y = name2)) +
  geom_col()
```






