---
title: "Section 6: Workflow"
format: html
---

## Section 6.1: R Projects and File Directories

```{r}
library(here)
here()
library(tidyverse)
athletes_df <- read_csv("data/athletesdata.csv")
athletes_test_read <- read_csv(here("data/athletesdata.csv"))
```

## Section 6.2: Code Style and Section 6.3: Debugging

```{r}
df1 <- mtcars |> filter(cyl == 4)
df2 <- mtcars |> filter(cyl == 6)
df3 <- mtcars |> filter(cyl == 8)
cars_with_4_cylinders_data_set <- mtcars |> filter(cyl == 4)
cyl4_df <- mtcars |> filter(cyl == 4)
cyl6.df <- mtcars |> filter(cyl == 6)
ggplot(data=mtcars,aes(x=wt,y=drat))+geom_point()+geom_smooth(method="lm",se=FALSE)
ggplot(data = mtcars, aes(x = wt, y = drat)) +
geom_point() +
geom_smooth(method = "lm", se = FALSE)
ggplot(data = mtcars, aes(x = wt, y = drat)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
mtcars |> filter(cyl == 4) |>
  group_by(vs) |>
  summarise(mean_mpg = mean(mpg, na.rm = TRUE))
mtcars |> filter(cyl == 4) |> group_by(vs) |> summarise(mean_mpg = mean(mpg, na.rm = TRUE))
cyl4_df <- mtcars |> filter(cyl == 4)

ggplot(data = cyl4_df, aes(x = mpg)) +
  geom_histogram()
```

## Section 6.4: Context and Outliers


```{r}
majors_df <- read_csv(here("data/majors.csv")) |>
  pivot_longer(-1, names_to = "year", values_to = "n_majors") |>
  mutate(year = as.numeric(year)) |>
  rename(major = `...1`)
head(majors_df)
spanish_df <- majors_df |> filter(major == "Mathematics")
ggplot(data = spanish_df, aes(x = year, y = n_majors)) +
  geom_line() +
  geom_smooth(se = FALSE)
int_econ_df <- majors_df |> filter(major == "Statistics")
ggplot(data = int_econ_df, aes(x = year, y = n_majors)) +
  geom_line() +
  geom_smooth(se = FALSE)
## using additional context about the data set
## to make more nuanced conclusions

## knowing some context about the data set can be 
## really helpful



library(skimr)
library(here)
videogame_df <- read_csv(here("data/videogame_clean.csv"))
## skim(videogame_df)
## commplete_rate is the proportion of rows
## that are non-missing for that variable
videogame_df |> summarise(mean_meta = mean(metascore, na.rm = TRUE),
                          med_meta = median(metascore, na.rm = TRUE))
## might not be reasonable to assume other 90%
## of video games would be similarly rated
## easier to think about if we know stuff about gaming

ggplot(data = videogame_df, aes(x = metascore, y = median_playtime)) +
  geom_point() +
  geom_smooth()
ggplot(data = videogame_df, aes(x = metascore, y = median_playtime)) +
  geom_point() +
  geom_smooth()

## skipping exercises 1-3
## exercise 4
videogame_df |>
  summarise(mean_play = mean(median_playtime, na.rm = TRUE),
            med_play = median(median_playtime, na.rm = TRUE))

videogame_df |>
  filter(median_playtime <= 1000) |>
  summarise(mean_play = mean(median_playtime, na.rm = TRUE),
            med_play = median(median_playtime, na.rm = TRUE))


## Hello! How do I get rid of the units from the values in
## my variable `x`? Thanks!
library(tidyverse)
test_df <- read_csv(here("data/parsedf.csv"))
head(test_df)
## Hello! How do I get rid of the units from the values in
## my variable `xvar`? Thanks!
library(tidyverse)
test_df2 <- tibble(xvar = c("20,000 dollars", "40 dollars"),
                   yvar = c(1, 2))
test_df2
```

```{r}
library(tidyverse)
toy_df <- tibble(Term = c("F19", "S20", "F19", "S21"))
toy_df
```

answer your reprex
```{r}
toy_df |> separate(Term, into = c("Semester", "Year"), sep = 1)
```


```{r}
videogame_df
## one person: make a reprex so that someone can help you find
## the first quartile of median playtime
toy_videogame <- tibble(median_playtime = c(1, 2, 8, 0, 1, NA, NA))
## hey, I need help finding the first quartile for playtime

## solve this reprex:
toy_videogame |>
  summarise(first_quart = quantile(median_playtime, 0.25))

videogame_df |>
  summarise(first_quart = quantile(median_playtime, 0.25))

## second person: make a reprex on how to make a table of the 
## price_cat variable
```