---
title: "Section 7: Base `R`"
author: "Matt Higham"
format: 
  html:
    embed-resources: true
---

## Class Exercises

Class Exercise 1.

```{r}
library(tidyverse)
fitness_df <- read_csv(here("data/higham_fitness_notclean.csv"))

weekday_vec <- c(2, 3, 4, 5, 6)
weekend_vec <- c(1, 7)

## weekday %in% weekend_vec is TRUE if the value of weekday
## is one of the values contained in weekend_vec
fitness_df |>
  mutate(weekend_ind = if_else(weekday %in% weekend_vec,
                               true = 1,
                               false = 0)) |>
  relocate(weekend_ind, weekday)
```

Class Exercise 2.

```{r}
set.seed(15125141)
toy_df <- tibble(xvar = rnorm(100, 3, 4),
                 yvar = rnorm(100, -5, 10),
                 group1 = sample(c("A", "B", "C"), size = 100, replace = TRUE),
                 group2 = sample(c("Place1", "Place2", "Place3"), size = 100,
                                 replace = TRUE))
toy_df
```

```{r}
toy_df
table(toy_df$group1)
toy_df |> group_by(group1) |>
  summarise(count = n()) |>
  pivot_wider(names_from = group1, values_from = count)



table(toy_df$group1, toy_df$group2)
toy_df |> group_by(group1, group2) |>
  summarise(count = n()) |>
  pivot_wider(names_from = group2, values_from = count) |>
  ungroup()



## group_by(more ) |> summarise() |> ????
```