---
title: "Section 7: Factors"
author: "Matt Higham"
format: 
  html:
    embed-resources: true
---

Class Exercise 1. Defense is quantitative and so we cannot see the spreads, the shapes of the distributions, outliers, sample size.

BGarplots and lollipop plots are useful for plotting counts of a categorical variable or totals.


Clsas Exercisew 2.

```{r}
library(tidyverse)
library(here)
pokemon_df <- read_csv(here("data/pokemon_allgen.csv")) |>
  mutate(Generation_cat = factor(Generation))

pokemon_nodup <- pokemon_df |> group_by(`#`) |> slice(1) |>
  ungroup()
##  for each pokemon # (the group by part), keep only the first
## row (slice(1)) -> this therefore drops all other rows for a 
## particular pokemon #.

## cleaner way
pokemon_df |> distinct(`#`, .keep_all = TRUE)
## keep only one row for each unique value of the variable(s) specified
```


Class Exercise 3.

```{r}
pokemon_nodup <- pokemon_df |> group_by(`#`) |> slice(1) |>
  ungroup()
pokemon_long <- pokemon_nodup |>
  pivot_longer(c(`Type 1`, `Type 2`),
               names_to = "Number",
               values_to = "Type")

pokemon_long <- pokemon_long |>
  filter(!is.na(Type)) |>
  mutate(Type_Deford = fct_reorder(.f = Type, .x = Defense,
                                   .fun = median))
ggplot(data = pokemon_long, aes(x = Type_Deford,
                               y = Defense)) +
  geom_boxplot() + 
  coord_flip()
## forcats functions *especially fct_reorder()) do not like groups:
## they will try to reorder the factor level within each group, which
## makes no sense
```

Class Exercise 4.

```{r}
path <- "https://raw.githubusercontent.com/highamm/ds234_quarto/main/data_online/"
medals_df <- read_csv(paste0(path, "medals.csv"))
medals_df

## 1.
medals_type <- medals_df |> group_by(medal_type, country) |>
  summarise(total_medals = n())

## 2
medals_total <- medals_df |> group_by(country) |> 
  summarise(total_medals = n()) |>
  arrange(desc(total_medals)) |>
  slice(1:15)

## 3: don't need to know yet
medals_heat <- semi_join(medals_type, medals_total, join_by(country == country))

## 4
medals_heat <- medals_heat |> ungroup() |>
  mutate(medal_type = fct_relevel(medal_type, c("Gold Medal", "Silver Medal", "Bronze Medal"))) |>
  mutate(country = fct_reorder(country, total_medals,
                               .fun = sum))
ggplot(data = medals_heat, aes(x = medal_type, y = country)) +
  geom_tile(aes(fill = total_medals)) +
  scale_fill_viridis_c() +
  scale_x_discrete(position = "top")
```


Your Turns

Your Turns 1 through 4.

```{r}
library(tidyverse)
library(here)
standings_df <- read_csv(here("data/standings.csv"))
standings_df |>
  relocate(playoffs)

table(standings_df$team_name)
## gives each level of the categorical variable and the number of times
## the level appears

## yt 2
standings_df <- standings_df |> mutate(team_name = fct_recode(team_name,
                                              Commanders = "Redskins"))
view(standings_df)

## yt 3
standings_df <- standings_df |> unite("franchise", c(team, team_name), sep = " ")

## spaces in the new factor levels mean I have to use backticks
standings_clean <- standings_df |>
  mutate(franchise = fct_collapse(franchise, 
                                  `St. Louis / LA Rams` = c("St. Louis Rams",
                                                          "Los Angeles Rams"),
                                  `San Diego / LA Chargers` = c("San Diego Chargers",
                                                              "Los Angeles Chargers")))

standings_clean |> relocate(playoffs)
```

```{r}
## strategy 1:
## keep only the rows with teams that made the playoffs
## then group by franchise so that you can count the number of times each 
## franchise mis in the "playoffs data set"
standings_t10 <- standings_clean |> filter(playoffs == "Playoffs") |>
  group_by(franchise) |>
  summarise(total_playoffs = n()) |>
  arrange(desc(total_playoffs)) |>
  slice(1:10) |>
  mutate(franchise = fct_reorder(franchise, total_playoffs))

ggplot(data = standings_t10, aes(x = total_playoffs, y = franchise)) +
  geom_segment(aes(x = 0, xend = total_playoffs, yend = franchise)) +
  geom_point() +
  theme_minimal()
## strategy 2:
## make an indicator variable that is 1 if the team made the playoffs and 0
## if they didn't. then group by franchise and add up our indicator variable.
standings_clean |> mutate(playoffs_ind = if_else(playoffs == "Playoffs", 
                                                 true = 1,
                                                 false = 0)) |>
  relocate(playoffs_ind) |>
  group_by(franchise) |>
  summarise(total_playoffs = sum(playoffs_ind)) |>
  arrange(desc(total_playoffs)) |>
  slice(1:10)


```



