---
title: "Section 9: Data Ethics"
author: "Matt Higham"
format: 
  html:
    embed-resources: true
---

## Class Exercises

Class Exercise 1. The purpose of this activity on course evaluations is to show that just because you do not put your name on something does not necessarily mean that that can't be traced back to you if you provide enough other identifying information.

Class Exercise 2.

b and d would be most inappropriate ethically because there is perhaps enough other identifying information that you would be able to determine what another student's grade in the class is.

a is more hazy ethically: there's not as much identifying information but it is still sharing student grades in the course that have a admittedly very low chance of being traced back to a student.

c seems more appropriate as it doesn't include any "sensitive" information like grade.

## Your Turn

Your Turn 1. In hypothesis confirmation, you are often testing one specific pre-determined hypothesis of interest (think STAT 113). For hypothesis generation, you can assess as many questions of interest as you would like and they don't need to be pre-determined (DATA/STAT 234). 

Your Turn 2. Hypothesis generation: as many times as you would like.  Hypothesis confirmation: just once (one test).

Your Turn 3.

a. Hypothesis confirmation: you have your one specific question of interest.

b. Hypothesis generation: you do not have a pre-determined event of interest.

c. Hypothesis generation: you are still exploring many different questions of interest related to seasonal trends.

