---
title: "Section 10: Data Import"
author: "Matt Higham"
format: 
  html:
    embed-resources: true
---

## Section 10.1: `read_csv()` from `readr`

```{r}
library(tidyverse)
library(here)
cars_df <- read_csv(here("data/mtcarsex.csv"))
head(cars_df)
```

```{r}
cars_df <- read_csv(here("data/mtcarsex.csv"),
                    skip = 2,
                    na = c("NA", "",
                           "-999"))
cars_df
## skip = 2 ignores the first two rows in the csv 
## when trying to read it in.
```

```{r}
read_csv(here("data/mtcarsex.csv"), na = c("NA", "-999"), skip = 2,
         col_types = cols(
  mpg = col_double(),
  cyl = col_factor(),
  disp = col_double(),
  hp = col_double(),
  drat = col_double(),
  wt = col_double(),
  qsec = col_double(),
  vs = col_logical(),
  am = col_logical(),
  gear = col_double(),
  carb = col_double()
)) |>
  slice(-1, -2)
```

Exercise 1.

```{r}
fitness_df <- read_csv(here::here("data/higham_fitness_notclean.csv"),
                       col_types = cols(
  Start = col_date(format = ""),
  active_cals = col_double(),
  distance = col_double(),
  flights = col_double(),
  steps = col_double(),
  month = col_factor(),
  weekday = col_factor(),
  dayofyear = col_double(),
  stepgoal = col_logical()
))

```

## Section 10.2: Data Scraping

```{r}
library(tidyverse)
library(rvest)

## provide the URL and name it something (in this case, url).
url <- "https://en.wikipedia.org/wiki/Gun_violence_in_the_United_States_by_state"

## read_html() convert the html code from the URL into something R can read
tab <- read_html(url) |> 
  html_nodes("table") ## html_nodes can grab only the tables 
tab[[1]] |> html_table()
tab[[2]] |> html_table()
```

```{r}
url <- "https://saintsathletics.com/sports/baseball/stats/2023"

tab <- read_html(url) |> html_nodes("table")
tab
obj <- tab[[1]] |> html_table()
obj
obj2 <- tab[[2]] |> html_table()
obj2
```

Exercise 2.

```{r}
url <- "https://www.stlawu.edu/offices/institutional-research/student-diversity-2021"

diversity_tab <- read_html(url) |> html_nodes("table")

diversity_tab[[1]] |> html_table()
```

## Section 10.3: JSON

Skip this but here for reference.

## Class Exercises

Class Exercise 1.

```{r}
library(tidyverse)
df <- read_delim(here("data/birthdays.txt"), delim = " - ",
                 skip = 4, 
                 col_names = c("date", "name", "species",
                               "time"),
                 na = c("?", "N/A", "", "NA"),
                 col_types = cols(
                   date = col_character(),
                   name = col_character(),
                   species = col_factor(),
                   time = col_character()
                 )) |>
  mutate(time = parse_number(time))
head(df)
```

Class Exercises 2 and 3. Skipped

Class Exercise 4.

```{r}
library(rvest)
url1 <- "https://en.wikipedia.org/wiki/Josh_Allen_(quarterback)"
tab_allen_stats <- read_html(url1) |> html_nodes("table")
allen_df <- tab_allen_stats[[6]] |> html_table()

## the issue here is that the table on wikipedia has
## a "double header," creating some duplicate column names
allen_stats <- tab_allen_stats[[6]] |> html_table(header = FALSE) 
allen_stats

## paste together the names from the first two rows
newnames <- paste(allen_stats[1, ], allen_stats[2, ])
## force the pasted names to be the "new" column names
allen_stats |> set_names(newnames) |>
  slice(-1, -2)
```

## Your Turn

Pick Your Turn 1 or Your Turn 2

Scrape in a table that you find interesting

Tidy your data frame (using separate() and/or parse_number())

Make a graph!

```{r}
animal_url <- "https://en.wikipedia.org/wiki/Animal_Crossing"
tab <- read_html(animal_url) |> html_nodes("table")
tab[[1]] |> html_table()

```