---
title: "Section 11: Import "
format: html
---

## Section 11.1: `readr`

```{r}
library(tidyverse)
library(here)
cars_df <- read_csv(here("data/mtcarsex.csv"))
head(cars_df)



cars_df <- read_csv(here("data/mtcarsex.csv"), skip = 2)
## first two lines will be skipped
head(cars_df)


cars_df <- read_csv(here("data/mtcarsex.csv"), na = c("NA", "-999"), skip = 2,
                    col_types = cols(
  mpg = col_double(),
  cyl = col_factor(),
  disp = col_double(),
  hp = col_double(),
  drat = col_double(),
  wt = col_double(),
  qsec = col_double(),
  vs = col_double(),
  am = col_double(),
  gear = col_double(),
  carb = col_double()
)) |>
  slice(-c(1, 2))

head(cars_df)
cars_df <- read_csv(here("data/mtcarsex.csv"), na = c(NA, "-999"), skip = 2,
  col_types = cols(
  mpg = col_double(),
  cyl = col_factor(),
  disp = col_double(),
  hp = col_double(),
  drat = col_double(),
  wt = col_double(),
  qsec = col_double(),
  vs = col_factor(),
  am = col_double(),
  gear = col_double(),
  carb = col_double()
))
cars_df <- read_csv(here("data/mtcarsex.csv"), na = c("NA", "-999"), skip = 2,
  col_types = cols(
  mpg = col_double(),
  cyl = col_factor(),
  disp = col_double(),
  hp = col_double(),
  drat = col_double(),
  wt = col_double(),
  qsec = col_double(),
  vs = col_factor(),
  am = col_double(),
  gear = col_double(),
  carb = col_double()
)) |>
  slice(-(1:2))
head(cars_df)
oscars_df <- read_tsv(here("data/oscars.tsv"))
head(oscars_df)
test_df <- read_csv(here("data/parsedf.csv"))
head(test_df)
test_df |> mutate(x2 = parse_number(x))
```

## Exercises 11.1.2

```{r}
## exercise 1
library(tidyverse)
df <- read_delim(here("data/birthdays.txt"), delim = " - ",
                 skip = 4, trim_ws = TRUE,
                 col_names = FALSE,
                 na = c("?", "N/A"),
                 col_types = cols(X4 = col_character())) |>
  mutate(X4 = parse_number(X4))
head(df)

## exercise 2
## install.packages("readxl")
library(readxl)
read_excel(here("data/evals_prof.xlsx"))

## exercise 3
## sheet = 2 tells R to read in the second sheet
## in the excel file
read_excel(here("data/evals_prof.xlsx"), sheet = 2)
```

## Section 11.2: Data Scraping

```{r}
library(tidyverse)
library(rvest)

## provide the URL and name it something (in this case, url).
url <- "https://en.wikipedia.org/wiki/Gun_violence_in_the_United_States_by_state"

## convert the html code into something R can read
h <- read_html(url)

## grabs the tables
tab <- h |> html_nodes("table") ## always be table

## tab[[1]] grabs the first table
test1 <- tab[[1]] |> html_table()
test2 <- tab[[2]] |> html_table()
test3 <- tab[[3]] |> html_table()
```

```{r}
## exercise: scrape from wikipedia page of your choice


head(test1)
head(test2)
head(test3)
url <- "https://saintsathletics.com/sports/baseball/stats/2021"
h <- read_html(url)
tab <- h |> html_nodes("table")
tab
obj <- tab[[1]] |> html_table(fill = TRUE)
head(obj)
tail(obj)
obj2 <- tab[[2]] |> html_table(fill = TRUE)
head(obj2)
tail(obj2)
```

```{r}
## install.packages("jsonlite")
library(jsonlite)
cr_cards <- fromJSON(here("data/clash_royale_card_info.json"))
library(tidyverse)
cr_cards_flat <- cr_cards[["cards"]]
cr_cards_df <- as_tibble(cr_cards_flat)
head(cr_cards_df)
cr_cards_flat2 <- purrr::flatten(cr_cards)
cr_cards_df2 <- as_tibble(cr_cards_flat2)
head(cr_cards_df2)
acedata <- fromJSON(here("data/ace.json"))
aceflat <- purrr::flatten(acedata)
head(aceflat)
```