---
title: "Section 13: stringr"
author: "Matt Higham"
format: 
  html:
    embed-resources: true
---

## Section 13.2

```{r}
library(here)
library(tidyverse)
med_djok_df <- read_csv(here("data/med_djok.csv"))
med_djok_df


## keeps any row where the point string has an @ symbol
## (which symbol;izes an unforced error)
med_djok_df |> filter(str_detect(point, pattern = "@") == TRUE)


med_djok_df |> filter(str_detect(point, pattern = "@") == TRUE) |>
  mutate(error_type = case_when(str_detect(point, pattern = "d@") ~ "deep error",
                                str_detect(point, pattern = "w@") ~ "wide error",
                                str_detect(point, pattern = "n@") ~ "net error")) |>
  group_by(PtWinner, error_type) |>
  summarise(n_errors = n())
```

Exercise 4.

```{r}
med_djok_df <- med_djok_df |>
  mutate(serve_location = case_when(str_detect(point, pattern = "^4") ~ "wide",
                                    str_detect(point, pattern = "^5") ~ "body",
                                    str_detect(point, pattern = "^6") ~ "down the center")) |>
  relocate(serve_location)
```

Your Turn 1

```{r}
med_djok_df |> relocate(isSvrWinner)
med_djok_sum <- med_djok_df |> group_by(serve_location, Serving) |>
  summarise(n_serves = n())

ggplot(data = med_djok_sum, aes(x = serve_location, y = n_serves)) +
  geom_col() +
  facet_wrap(~ Serving)

## Your Turn 2
med_djok_sum2 <- med_djok_df |> group_by(serve_location, Serving) |>
  summarise(prop_win = mean(isSvrWinner))
ggplot(data = med_djok_sum2, aes(x = serve_location, y = prop_win)) +
  geom_col() +
  facet_wrap(~ Serving)

## option 2
med_djok_sum3 <- med_djok_df |> group_by(serve_location, Serving, isSvrWinner) |>
  summarise(n_serves = n())

ggplot(data = med_djok_sum3, aes(x = serve_location, y = n_serves)) +
  geom_col(aes(fill = factor(isSvrWinner))) +
  facet_wrap(~ Serving) +
  scale_fill_viridis_d()

## skip your turn 3
```

## Class Exercises

```{r}
library(schrute)
library(tidyverse)
office_df <- schrute::theoffice |> tibble()
## tibble() makes sure this prints "nicely"
office_df
## character column gives the name of the speaking charcter
## text column gives the character's spoken line
```

```{r}
library(tidytext)
office_unnest <- office_df |> unnest_tokens(output = "word", input = "text")
office_kelly <- office_unnest |> filter(character == "Kelly")

## filter out stop words (using stop_words data frame in tidytext)
kelly_nostop <- anti_join(office_kelly, stop_words, by = join_by(word == word))

kelly_top15 <- kelly_nostop |> group_by(word) |>
  summarise(num_word = n()) |>
  arrange(desc(num_word)) |>
  slice(1:15) |>
  mutate(word = fct_reorder(word, num_word))

ggplot(data = kelly_top15, aes(x = num_word, y = word)) +
  geom_segment(aes(x = 0, xend = num_word, y = word, yend = word)) +
  geom_point() +
  theme_minimal()
```

```{r}
office_num_episodes <- office_df |> group_by(season) |>
  filter(episode == max(episode)) |>
  slice(1) |>
  mutate(season = factor(season))

kelly_seasons <- office_kelly |> group_by(season) |> summarise(num_words = n()) |>
  mutate(season = factor(season)) |>
  mutate(season = fct_rev(season))

kelly_seasons <- left_join(kelly_seasons, office_num_episodes,
          by = join_by(season == season)) |>
  mutate(words_per_episode = num_words / episode)

ggplot(data = kelly_seasons, aes(x = words_per_episode, y = season))  +
  geom_segment(aes(x = 0, xend = words_per_episode, y = season, yend = season)) +
  geom_point() +
  theme_minimal()
  
```