---
title: "Section 13: Text Data and Strings"
author: "Matt Higham"
format: 
  html:
    embed-resources: true
---

## Section 14.2: `stringr`

```{r}
library(here)
library(tidyverse)
med_djok_df <- read_csv(here("data/med_djok.csv"))
med_djok_df

med_djok_df |>
  mutate(serve_location = case_when(str_detect(point, pattern = "^4") ~ "wide",
                                    str_detect(point, pattern = "^5") ~ "body",
                                    str_detect(point, pattern = "^6") ~ "down the center")) |>
  relocate(serve_location)
```

## Class Exercises

Class Exercise 1

```{r}
## install.packages("schrute")
library(schrute)
library(tidyverse)

schrute::theoffice
```

```{r}
library(tidytext)
office_unnest <- theoffice |>
  unnest_tokens(output = "word", input = "text")
office_unnest

## stop_words gets loaded in when you load
## in the tidytext package
office_stop <- anti_join(office_unnest, stop_words,
                          by = join_by(word == word))

office_sum <- office_stop |> 
  filter(character == "Michael") |>
  group_by(word) |>
  summarise(n = n()) |>
  arrange(desc(n)) |>
  slice(1:20) |>
  mutate(word = fct_reorder(word, n))

ggplot(data = office_sum, aes(x = word, y = n)) +
  geom_segment(aes(xend = word, y = 0, yend = n)) +
  geom_point() +
  theme_minimal() +
  coord_flip()

```

## Your Turn

Your Turn 1.

```{r}
med_djok_df |>
  mutate(serve_location = case_when(str_detect(point, pattern = "^4") ~ "wide",
                                    str_detect(point, pattern = "^5") ~ "body",
                                    str_detect(point, pattern = "^6") ~ "down the center")) |>
  group_by(Serving, serve_location) |>
  summarise(n_count = n())
```

Your Turn 3.

```{r}
med_djok_df |>
  mutate(is_volley = if_else(str_detect(point, pattern = "v") |
                               str_detect(point, pattern = "z") |
                               str_detect(point, pattern = "i") |
                               str_detect(point, pattern = "k"),
                             true = 1, 
                             false = 0)) |>
  relocate(is_volley) |>
  summarise(prop_volley = mean(is_volley))
```


