---
title: "Don't Use the Play Button!!"
format: html
---

```{r}
library(tidyverse)
library(readxl)
library(here)

majors_unclean <- read_xlsx(here("data/graduates_2022.xlsx"), sheet = 1, skip = 1)
majors_only <- majors_unclean |> filter(row_number() %in% 1:90 | `...1` == "GRADUATES") |>
  filter(!is.na(`...1`)) |>
  select(1, 2, starts_with("20")) |>
  select(c(1, 3:25))

majors_graduates <- majors_only |>
  pivot_longer(2:24, names_to = "year", values_to = "majors") |>
  mutate(year = parse_number(str_trunc(year, 7))) |>
  rename(major = "...1", 
         n_majors = majors)

majors_df <- majors_graduates |> filter(major != "GRADUATES")
graduates_df <- majors_graduates |> filter(major == "GRADUATES") |>
  select(-major)

slumajors_df <- left_join(majors_df, graduates_df, by = "year") |> 
  rename(n_majors = n_majors.x,
         n_graduates = n_majors.y)
slumajors_df
```


## example 1

```{r}
library(tidyverse)
library(readxl)
library(here)

majors_unclean <- read_xlsx(here("data/graduates_2022.xlsx"), sheet = 1, skip = 1)
majors_only <- majors_unclean |> filter(row_number() %in% 1:90 | `...1` == "GRADUATES") |>
  filter(!is.na(`...1`)) |>
  select(1, 2, starts_with("20")) |>
  select(c(1, 3:25))

majors_graduates <- majors_only |>
  pivot_longer(2:25, names_to = "year", values_to = "majors") |>
  mutate(year = parse_number(str_trunc(year, 7))) |>
  rename(major = "...1", 
         n_majors = majors)

majors_df <- majors_graduates |> filter(major != "GRADUATES")
graduates_df <- majors_graduates |> filter(major == "GRADUATES") |>
  select(-major)

slumajors_df <- left_join(majors_df, graduates_df, by = "year") |> 
  rename(n_majors = n_majors.x,
         n_graduates = n_majors.y)
slumajors_df
```

## example 2

```{r}
library(tidyverse)
library(readxl)
library(here)

majors_unclean <- read_xlsx(here("data/graduates_2022.xlsx"), sheet = 1, skip = 1)
majors_only <- majors_unclean |> filter(row_number() %in% 1:90 | `...1` == "GRADUATES") |>
  filter(!is.na(`...1`)) |>
  select(1, 2, starts_with("20")) |>
  select(c(1, 3:25))

majors_graduates <- majors_only |>
  pivot_longer(2:24, names_to = "year", values_to = "majors") |>
  mutate(year = parse_number(str_trunc(year, 7))) |>
  rename(major = "...1", 
         n_majors = majors)

majors_df <- majors_graduates |> filter(major != "graduates")
graduates_df <- majors_graduates |> filter(major == "graduates") |>
  select(-major)

slumajors_df <- left_join(majors_df, graduates_df, by = "year") |> 
  rename(n_majors = n_majors.x,
         n_graduates = n_majors.y)
slumajors_df
```



## example 3

```{r}
library(tidyverse)
library(readxl)
library(here)

majors_unclean <- read_xlsx(here("data/graduates_2022.xlsx"), sheet = 1, skip = 1)
majors_only <- majors_unclean |> filter(row_number() %in% 1:90 | `...1` == "GRADUATES") |>
  filter(!is.na(`...1`)) |>
  select(1, 2, starts_with("20")) |>
  select(c(1, 3:26))

majors_graduates <- majors_only |>
  pivot_longer(2:24, names_to = "year", values_to = "majors") |>
  mutate(year = parse_number(str_trunc(year, 7))) |>
  rename(major = "...1", 
         n_majors = majors)

majors_df <- majors_graduates |> filter(major != "GRADUATES")
graduates_df <- majors_graduates |> filter(major == "GRADUATES") |>
  select(-major)

slumajors_df <- left_join(majors_df, graduates_df, by = "year") |> 
  rename(n_majors = n_majors.x,
         n_graduates = n_majors.y)
slumajors_df
```
